In [ ]:
import numpy as np

In [ ]:
list(),str(),tuple(),set(),dict()

([], '', (), set(), {})

In [ ]:
y=np.array([1,2,3])

In [ ]:
x=[1,2,3]

In [ ]:
type(x),type(y)

(list, numpy.ndarray)

In [ ]:
x/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
y/2

array([0.5, 1. , 1.5])

In [ ]:
x=[1,2,3,"data science"]

In [ ]:
x

[1, 2, 3, 'data science']

In [ ]:
type(x[0]),type(x[1]),type(x[2]),type(x[3])

(int, int, int, str)

In [ ]:
y=np.array([1,2,3,3.6,"data"])

In [ ]:
type(y[0]),type(y[1]),type(y[2]),type(y[3]),type(y[4])

(numpy.str_, numpy.str_, numpy.str_, numpy.str_, numpy.str_)

In [ ]:
### as in 22 --1,2 are int and 3.6 is a float and "data" it is a string..so as the last value is string ..it prints all the values as numpy.str

In [ ]:
y

array(['1', '2', '3', '3.6', 'data'], dtype='<U32')

In [ ]:
for i in range(0,10):
  print(np.random.randint(0,10))

5
7
0
4
0
4
6
3
8
3


In [ ]:
### here rand int refers to RANDOM INTEGERS....

In [ ]:
np.random.randint(0,10,(5,5)) ### it prints random values from 0 to 10 in a (5,5) that means ROWS AND COLUMNS

array([[5, 2, 1, 6, 2],
       [7, 7, 3, 5, 0],
       [8, 9, 6, 2, 7],
       [5, 1, 2, 8, 8],
       [8, 1, 7, 6, 8]])

In [ ]:
data=np.random.randint(0,100,(5,5))

In [ ]:
data

array([[36, 98, 88, 55, 33],
       [24, 63, 93, 82, 92],
       [89, 86,  0, 99, 10],
       [51, 79, 12, 74, 45],
       [15, 51, 89, 12, 88]])

In [ ]:
data[0:3,4:5]

array([[33],
       [92],
       [10]])

In [ ]:
data[-5:-4,-5:-4]

array([[36]])

In [ ]:
data[-4:-2,-3:-2]

array([[93],
       [ 0]])

In [ ]:
data[0,:]

array([36, 98, 88, 55, 33])

In [ ]:
data[:,0]

array([36, 24, 89, 51, 15])

In [ ]:
data.shape


(5, 5)

In [ ]:
data.size

25

In [ ]:
data.T ### T IA A TRANSPOSE

array([[36, 24, 89, 51, 15],
       [98, 63, 86, 79, 51],
       [88, 93,  0, 12, 89],
       [55, 82, 99, 74, 12],
       [33, 92, 10, 45, 88]])

In [ ]:
data

array([[36, 98, 88, 55, 33],
       [24, 63, 93, 82, 92],
       [89, 86,  0, 99, 10],
       [51, 79, 12, 74, 45],
       [15, 51, 89, 12, 88]])

In [ ]:
x=2

In [ ]:
data**2

array([[1296, 9604, 7744, 3025, 1089],
       [ 576, 3969, 8649, 6724, 8464],
       [7921, 7396,    0, 9801,  100],
       [2601, 6241,  144, 5476, 2025],
       [ 225, 2601, 7921,  144, 7744]])

In [ ]:
x=np.random.randint(0,10,(3,3))
y=np.random.randint(0,10,(3,3))

In [ ]:
x

array([[6, 6, 4],
       [3, 3, 5],
       [1, 5, 2]])

In [ ]:
y

array([[8, 7, 5],
       [5, 2, 0],
       [9, 5, 0]])

In [ ]:
np.add(x,2)

array([[8, 8, 6],
       [5, 5, 7],
       [3, 7, 4]])

In [ ]:
np.add(2,x)

array([[8, 8, 6],
       [5, 5, 7],
       [3, 7, 4]])

In [ ]:
np.multiply(x,2)

array([[12, 12,  8],
       [ 6,  6, 10],
       [ 2, 10,  4]])

In [ ]:
np.divide(x,2)

array([[3. , 3. , 2. ],
       [1.5, 1.5, 2.5],
       [0.5, 2.5, 1. ]])

In [ ]:
np.floor_divide(x,2)

array([[3, 3, 2],
       [1, 1, 2],
       [0, 2, 1]])

In [ ]:
np.exp(x)

array([[403.42879349, 403.42879349,  54.59815003],
       [ 20.08553692,  20.08553692, 148.4131591 ],
       [  2.71828183, 148.4131591 ,   7.3890561 ]])

In [ ]:
np.pow(x,2)

array([[36, 36, 16],
       [ 9,  9, 25],
       [ 1, 25,  4]])

In [ ]:
np.random.rand(5,5)

array([[0.36875404, 0.24018463, 0.68553667, 0.02719586, 0.01894168],
       [0.35634932, 0.89261269, 0.79600083, 0.4041899 , 0.3978882 ],
       [0.53102057, 0.10021084, 0.75625289, 0.70524639, 0.4045606 ],
       [0.066363  , 0.67364939, 0.02039667, 0.04431137, 0.31897242],
       [0.52533525, 0.39895369, 0.39006311, 0.17813423, 0.91091207]])

In [ ]:
np.random.randn(1300,1300).std()

np.float64(0.9990743306663703)

In [ ]:
np.eye(5)   ### it is a identity matrix, diagonal(1)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
data=np.random.randint(0,10,(5,5))

In [ ]:
data

array([[0, 8, 8, 4, 9],
       [8, 8, 8, 5, 4],
       [6, 1, 2, 8, 5],
       [1, 3, 5, 0, 3],
       [6, 8, 4, 7, 0]])

In [ ]:
print(data.sum())
print(data.min())
print(data.max())
print(data.mean())
print(data.std())

121
0
9
4.84
2.9076450952618


In [ ]:
data.argmax()

np.int64(4)

In [ ]:
data=np.random.randint(0,10,(3,3))

In [ ]:
data

array([[5, 5, 6],
       [5, 1, 9],
       [8, 8, 9]])

In [ ]:
data.sum(axis=1)

array([16, 15, 25])

In [ ]:
data.sum(axis=0)

array([18, 14, 24])

In [ ]:
data

array([[5, 5, 6],
       [5, 1, 9],
       [8, 8, 9]])

In [ ]:
data.argmin(axis=1)

array([0, 1, 0])

In [ ]:
data.max(axis=0)

array([8, 8, 9])