In [2]:
import numpy as np

In [ ]:
#  Retsil dataset as numpy array

In [11]:
retail_np_array=np.array([
   [1001,"laptop",1,50000,50000],
   [1002,"mouse",2,500,1000],
   [1003,"keyboard",1,1000,1000],
   [1004,"monitor",2,7000,14000],
   [1005,"headphones",1,2000,2000]
])


In [12]:
retail_np_array

array([['1001', 'laptop', '1', '50000', '50000'],
       ['1002', 'mouse', '2', '500', '1000'],
       ['1003', 'keyboard', '1', '1000', '1000'],
       ['1004', 'monitor', '2', '7000', '14000'],
       ['1005', 'headphones', '1', '2000', '2000']], dtype='<U21')

In [14]:
retail_np_array=np.array([
   [1001,"laptop",1,50000,50000],
   [1002,"mouse",2,500,1000],
   [1003,"keyboard",1,1000,1000],
   [1004,"monitor",2,7000,14000],
   [1005,"headphones",1,2000,2000]
] ,dtype=object)

In [22]:
retail_np_array.size

25

In [25]:
retail_np_array.shape

(5, 5)

In [28]:
retail_np_array.shape[0]

5

In [30]:
retail_np_array.shape[ :3]

(5, 5)

In [15]:
retail_np_array            #object datatype

array([[1001, 'laptop', 1, 50000, 50000],
       [1002, 'mouse', 2, 500, 1000],
       [1003, 'keyboard', 1, 1000, 1000],
       [1004, 'monitor', 2, 7000, 14000],
       [1005, 'headphones', 1, 2000, 2000]], dtype=object)

In [17]:
##Extracting columns
customer_ids=retail_np_array[:,0]
products=retail_np_array[:,1]
quantities=retail_np_array[:,2].astype(int)
prices=retail_np_array[:,3].astype(int)
totals=retail_np_array[:,4].astype(int)

In [19]:
customer_ids=retail_np_array[:,0]
customer_ids

array([1001, 1002, 1003, 1004, 1005], dtype=object)

In [20]:
products=retail_np_array[:,1]
products

array(['laptop', 'mouse', 'keyboard', 'monitor', 'headphones'],
      dtype=object)

In [31]:
retail_np_array=np.array([
   [1001,"laptop",1,50000,50000],
   [1002,"mouse",2,500,1000],
   [1003,"keyboard",1,1000,1000],
   [1004,"monitor",2,7000,14000],
   [1005,"headphones",1,2000,2000]
] ,dtype=object)

In [32]:
retail_np_array

array([[1001, 'laptop', 1, 50000, 50000],
       [1002, 'mouse', 2, 500, 1000],
       [1003, 'keyboard', 1, 1000, 1000],
       [1004, 'monitor', 2, 7000, 14000],
       [1005, 'headphones', 1, 2000, 2000]], dtype=object)

In [56]:
customer_ids=retail_np_array[:,0]
products=retail_np_array[:,1]
quantities=retail_np_array[:,2].astype(int)
prices=retail_np_array[:,3].astype(int)
totals=retail_np_array[:,4].astype(int)

In [57]:
tota_number_of_transactions=retail_np_array.shape[0]

In [58]:
tota_number_of_transactions

5

In [60]:
total_revenue_generate=np.sum(totals)

In [61]:
total_revenue_generate

np.int64(68000)

In [62]:
average_order_value=np.mean(totals)

In [63]:
average_order_value

np.float64(13600.0)

In [64]:
product_with_the_highest_total_price=products[np.argmax(totals)]

In [65]:
product_with_the_highest_total_price

'laptop'

In [66]:
product_with_the_lowest_total_price=products[np.argmin(totals)]

In [43]:
product_with_the_lowest_total_price

'mouse'

In [44]:
average_price_of_products=np.mean(prices)

In [45]:
average_price_of_products

np.float64(12100.0)

In [46]:
total_quantity_sold=np.sum(quantities)

In [47]:
total_quantity_sold

np.int64(7)

In [49]:
most_frequently_purchased_product=np.unique(products,return_counts=True)

In [50]:
most_frequently_purchased_product

(array(['headphones', 'keyboard', 'laptop', 'monitor', 'mouse'],
       dtype=object),
 array([1, 1, 1, 1, 1]))

In [51]:
number_of_unique_products=len(np.unique(products))

In [52]:
number_of_unique_products

5

In [53]:
number_of_unique_customers=len(np.unique(customer_ids))

In [54]:
number_of_unique_customers

5